(()=>{
 const book=document.querySelector('.zine-spread'),left=book.querySelector('.left-page'),right=book.querySelector('.right-page'),prev=document.querySelector('#prev-page'),next=document.querySelector('#next-page'),status=document.querySelector('#page-status');let index=0,busy=false,startX=null;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 function paint(el,page){el.style.backgroundImage=`url("assets/jeju/${Math.floor(page/2)+1}.jpg")`;el.style.backgroundPosition=page%2?'right center':'left center';el.setAttribute('role','img');el.setAttribute('aria-label',`Jeju page ${page+1}${page===0?' — Cover':page===15?' — Back cover':''}`);}
 function render(){book.classList.toggle('is-cover',index===0||index===8);if(index===0)paint(right,0);else if(index===8)paint(right,15);else{paint(left,index*2-1);paint(right,index*2);}prev.disabled=index===0;next.disabled=index===8;next.textContent=index===0?'Open →':'Next →';status.textContent=index===0?'Cover · 01 / 16':index===8?'Back cover · 16 / 16':`${String(index*2).padStart(2,'0')}–${String(index*2+1).padStart(2,'0')} / 16`;}
 async function turn(direction){if(busy||index+direction<0||index+direction>8)return;busy=true;const old=index;const source=direction>0?right:left;const leaf=document.createElement('div');leaf.className='turning-leaf';leaf.style.backgroundImage=source.style.backgroundImage;leaf.style.backgroundPosition=source.style.backgroundPosition;leaf.style.left=direction>0?'50%':'0';leaf.style.transformOrigin=direction>0?'left center':'right center';if(old===0||old===8){leaf.style.width='100%';leaf.style.left='0';}book.append(leaf);index+=direction;render();if(!reduced.matches){try{await leaf.animate([{transform:'rotateY(0deg)',filter:'brightness(1)'},{transform:`rotateY(${direction>0?-165:165}deg)`,filter:'brightness(.65)'}],{duration:720,easing:'cubic-bezier(.3,.05,.2,1)',fill:'forwards'}).finished;}catch{}}leaf.remove();busy=false;}
 prev.onclick=()=>turn(-1);next.onclick=()=>turn(1);left.onclick=()=>turn(-1);right.onclick=()=>turn(index===8?-1:1);
 document.addEventListener('keydown',e=>{if(document.body.classList.contains('about-open')||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight'){e.preventDefault();turn(1);}if(e.key==='ArrowLeft'){e.preventDefault();turn(-1);}});
 book.addEventListener('touchstart',e=>startX=e.touches[0].clientX,{passive:true});book.addEventListener('touchend',e=>{if(startX===null)return;const d=e.changedTouches[0].clientX-startX;startX=null;if(Math.abs(d)>45){turn(d<0?1:-1);}},{passive:true});
 for(let n=1;n<=8;n++){const img=new Image();img.src=`assets/jeju/${n}.jpg`;}
 render();
})();
